<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>greetings subtitle</name>
   <tag></tag>
   <elementGuidId>e904c78b-17ad-4bca-94b0-4867ff9e190b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='greetings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#greetings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f7d9a5fd-3f7f-45cc-bf88-350cfa5219f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greetings</value>
      <webElementGuid>a1c6ec61-16ce-4bd5-a627-7bf04e74a2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello Shiran Daniel, let's complete the test form:</value>
      <webElementGuid>343bf460-639a-44e9-b8d5-9c916c1e81e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greetings&quot;)</value>
      <webElementGuid>9cb888ba-8900-4048-87cd-60de5b5c1534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='greetings']</value>
      <webElementGuid>d7d63a14-cd1f-4378-85dd-2ca5584a82b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageProfile']/p</value>
      <webElementGuid>355c8d15-1e4b-4bc7-94d8-8a4199f49b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestProject Example page'])[2]/following::p[1]</value>
      <webElementGuid>df0d88fa-a786-41e4-afd1-e645a7fc5cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>59f3ba2d-a665-4dc2-829b-72a73a8e0db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::p[1]</value>
      <webElementGuid>a63b4886-e5e0-41ce-a4ed-280f748568bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>b026f850-bc11-407e-9cd7-2085196644b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>f0c626e1-1fd2-4301-ba13-f35830b00228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'greetings' and (text() = concat(&quot;Hello Shiran Daniel, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;) or . = concat(&quot;Hello Shiran Daniel, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;))]</value>
      <webElementGuid>dba8186c-8779-4d6a-8b2a-a733d8537d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
